name: Build Executables

on:
  push:
    branches:
      - initial
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build Windows executable
        run: |
          make dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MechAnalyser
          path: dist/*

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print CPU architecture
        run: uname -m

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build macOS executable
        run: |
          make dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MechAnalyser
          path: dist/*

  build-macos-x86_64:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print CPU architecture
        run: uname -m

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build macOS executable
        run: |
          make dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MechAnalyser
          path: dist/*
